const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const toast=(m)=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)};
const state=JSON.parse(localStorage.getItem('stampiioDemo')||'null')||{points:250,customers:[['Yasine B.','yasine@email.com','250','Actif'],['Emma L.','emma@email.com','180','Actif'],['Lucas D.','lucas@email.com','80','Actif'],['Sophie M.','sophie@email.com','320','VIP']],rewards:[['Boisson offerte',300,12,true],['Dessert offert',500,8,true],['-10 % sur l’addition',750,5,true]],transactions:[['Yasine B.','+50','Gain','Aujourd’hui 10:24'],['Emma L.','+20','Gain','Aujourd’hui 10:15'],['Lucas D.','-100','Récompense','Hier 18:42'],['Sophie M.','+30','Gain','Hier 16:09']]};
const save=()=>localStorage.setItem('stampiioDemo',JSON.stringify(state));
$$('[data-open]').forEach(b=>b.onclick=()=>$('#'+b.dataset.open).classList.add('open'));
$$('.modal-close').forEach(b=>b.onclick=()=>b.closest('.modal').classList.remove('open'));
$$('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)m.classList.remove('open')});
$('#menuBtn').onclick=()=>$('.site-header').classList.toggle('open');
$('#loginForm').onsubmit=e=>{e.preventDefault();openApp('dashboard')};
$('#contactForm').onsubmit=e=>{e.preventDefault();e.target.closest('.modal').classList.remove('open');e.target.reset();toast('Votre demande a bien été envoyée.')};
$$('[data-demo]').forEach(b=>b.onclick=()=>openApp(b.dataset.demo));
function openApp(view='dashboard'){$$('.modal').forEach(m=>m.classList.remove('open'));$('#publicSite').classList.add('hidden');$('#publicHeader').classList.add('hidden');$('#publicFooter').classList.add('hidden');$('#appShell').classList.remove('hidden');render(view);window.scrollTo(0,0)}
$('#logoutBtn').onclick=()=>{$('#appShell').classList.add('hidden');$('#publicSite').classList.remove('hidden');$('#publicHeader').classList.remove('hidden');$('#publicFooter').classList.remove('hidden');window.scrollTo(0,0)};
$('#mobileSide').onclick=()=>$('.sidebar').classList.toggle('open');
$$('#appNav button').forEach(b=>b.onclick=()=>{render(b.dataset.view);$('.sidebar').classList.remove('open')});
function setNav(view){$$('#appNav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const b=$(`#appNav button[data-view="${view}"]`);$('#appCrumb').textContent=b?b.textContent.trim():'Stampiio'}
function render(view){setNav(view);const f=views[view]||views.dashboard;$('#viewContainer').innerHTML=f();bindView(view)}
const kpi=(label,value,delta='')=>`<div class="kpi"><small>${label}</small><strong>${value}</strong>${delta?`<span class="delta">${delta}</span>`:''}</div>`;
const views={
dashboard:()=>`<div class="view"><div class="view-head"><div><h1>Bonjour Yasine 👋</h1><p>Voici un aperçu de l’activité de votre programme.</p></div><button class="btn btn-primary" data-go="scanner">Scanner un client</button></div><div class="kpi-grid">${kpi('Clients actifs','248','+12 ce mois')}${kpi('Points distribués','3 750','+8 % ce mois')}${kpi('Récompenses utilisées','32','+4 ce mois')}${kpi('Cartes Wallet','221','89 % des clients')}</div><div class="dash-grid"><section class="panel"><h3>Évolution des inscriptions</h3><div class="chart">${[28,40,55,48,70,62,82,95,88,115,132,148].map(v=>`<span style="height:${v}px"></span>`).join('')}</div></section><section class="panel"><h3>Dernières transactions</h3><table class="data-table">${state.transactions.slice(0,5).map(x=>`<tr><td><b>${x[0]}</b><br><small>${x[3]}</small></td><td><span class="badge ${x[2]==='Gain'?'green':'red'}">${x[1]} pts</span></td></tr>`).join('')}</table></section></div></div>`,
customers:()=>`<div class="view"><div class="view-head"><div><h1>Clients</h1><p>Gérez les membres de votre programme.</p></div><div class="toolbar"><input class="search" id="customerSearch" placeholder="Rechercher..."><button class="btn btn-primary" id="addCustomer">+ Ajouter</button></div></div><section class="panel"><table class="data-table"><thead><tr><th>Client</th><th>E-mail</th><th>Points</th><th>Statut</th><th></th></tr></thead><tbody id="customerRows">${customerRows(state.customers)}</tbody></table></section></div>`,
transactions:()=>`<div class="view"><div class="view-head"><div><h1>Transactions</h1><p>Historique complet des gains et récompenses.</p></div><button class="btn btn-secondary" id="exportBtn">Exporter CSV</button></div><section class="panel"><table class="data-table"><thead><tr><th>Client</th><th>Mouvement</th><th>Type</th><th>Date</th></tr></thead><tbody>${state.transactions.map(x=>`<tr><td>${x[0]}</td><td><b>${x[1]} pts</b></td><td><span class="badge ${x[2]==='Gain'?'green':'red'}">${x[2]}</span></td><td>${x[3]}</td></tr>`).join('')}</tbody></table></section></div>`,
rewards:()=>`<div class="view"><div class="view-head"><div><h1>Récompenses</h1><p>Créez les avantages proposés à vos clients.</p></div><button class="btn btn-primary" id="addReward">+ Créer une récompense</button></div><section class="panel"><table class="data-table"><thead><tr><th>Nom</th><th>Coût</th><th>Utilisations</th><th>Statut</th><th></th></tr></thead><tbody>${state.rewards.map((r,i)=>`<tr><td><b>${r[0]}</b></td><td>${r[1]} points</td><td>${r[2]}</td><td><span class="badge ${r[3]?'green':'red'}">${r[3]?'Active':'Inactive'}</span></td><td><button class="btn btn-ghost reward-toggle" data-i="${i}">${r[3]?'Désactiver':'Activer'}</button></td></tr>`).join('')}</tbody></table></section></div>`,
program:()=>`<div class="view"><div class="view-head"><div><h1>Personnalisation de la carte</h1><p>Modifiez le contenu et l’apparence de votre carte Wallet.</p></div><button class="btn btn-primary" id="saveProgram">Enregistrer</button></div><div class="editor-grid"><div><section class="panel"><h3>Informations</h3><div class="form-grid"><label>Nom du commerce<input id="businessName" value="LE PETIT CAFÉ"></label><label>Nom du programme<input id="programName" value="CARTE DE FIDÉLITÉ"></label><label>Points de récompense<input id="rewardThreshold" type="number" value="300"></label><label>Récompense<input id="rewardName" value="1 boisson offerte"></label><label>Couleur principale<input id="colorA" type="color" value="#7b3cff"></label><label>Couleur secondaire<input id="colorB" type="color" value="#4a55ee"></label></div></section><section class="panel" style="margin-top:16px"><h3>Règles</h3><div class="form-grid"><label>Mécanique<select><option>Points</option><option>Tampons</option><option>Visites</option></select></label><label>Valeur par achat<input value="1 € = 1 point"></label></div></section></div><aside class="wallet-preview"><div class="preview-card" id="previewCard"><div class="title" id="pBusiness">LE PETIT CAFÉ</div><div class="sub" id="pProgram">CARTE DE FIDÉLITÉ</div><div class="big">${state.points}</div><small>POINTS</small><p>Prochaine récompense : <b id="pReward">300 points = 1 boisson offerte</b></p><div class="barcode">▮▯▮▮▯▮▯▯▮▮▮▯▮▯▮</div></div><button class="wallet-add"> Ajouter à Apple Wallet</button><button class="wallet-add google">G Ajouter à Google Wallet</button></aside></div></div>`,
scanner:()=>`<div class="view"><div class="view-head"><div><h1>Scanner un client</h1><p>Utilisez la caméra ou lancez le scan de démonstration.</p></div></div><div class="scanner-layout"><div class="scanner-box"><div class="scan-frame"><div class="scan-line"></div><div class="scan-code">⌗</div></div></div><section class="panel customer-card"><div class="avatar">YB</div><h2>Yasine B.</h2><small>Membre depuis juillet 2026</small><div class="big-balance" id="scanBalance">${state.points} pts</div><div class="stamp-row">${Array.from({length:10},(_,i)=>`<span class="stamp ${i<6?'filled':''}">${i<6?'✓':i+1}</span>`).join('')}</div><div class="toolbar" style="justify-content:center"><button class="btn btn-primary" id="addPoints">+ 10 points</button><button class="btn btn-secondary" id="useReward">Utiliser 300 points</button></div></section></div></div>`,
employees:()=>`<div class="view"><div class="view-head"><div><h1>Employés</h1><p>Gérez les accès de votre équipe.</p></div><button class="btn btn-primary" id="inviteEmployee">Inviter un employé</button></div><section class="panel"><table class="data-table"><tr><th>Nom</th><th>Rôle</th><th>Dernière activité</th><th>Statut</th></tr><tr><td>Yasine Souayah</td><td>Administrateur</td><td>Maintenant</td><td><span class="badge green">Actif</span></td></tr><tr><td>Léa Girard</td><td>Employée</td><td>Aujourd’hui 10:24</td><td><span class="badge green">Actif</span></td></tr><tr><td>Karim B.</td><td>Employé</td><td>Hier 18:42</td><td><span class="badge green">Actif</span></td></tr></table></section></div>`,
settings:()=>`<div class="view"><div class="view-head"><div><h1>Paramètres</h1><p>Gérez votre commerce et votre abonnement.</p></div></div><div class="settings-tabs"><button class="active">Commerce</button><button>Abonnement</button><button>Sécurité</button></div><section class="panel"><div class="form-grid"><label>Nom commercial<input value="Le Petit Café"></label><label>SIRET<input value="123 456 789 00012"></label><label>E-mail<input value="contact@lepetitcafe.fr"></label><label>Téléphone<input value="01 23 45 67 89"></label><label>Adresse<input value="12 rue du Marché, Paris"></label><label>Formule<select><option>Pro — 39,90 €/mois</option></select></label></div><button class="btn btn-primary" id="saveSettings">Enregistrer les modifications</button></section></div>`};
function customerRows(rows){return rows.map((c,i)=>`<tr><td><b>${c[0]}</b></td><td>${c[1]}</td><td>${c[2]}</td><td><span class="badge green">${c[3]}</span></td><td><button class="btn btn-ghost delete-customer" data-i="${i}">Supprimer</button></td></tr>`).join('')}
function bindView(view){$$('[data-go]').forEach(b=>b.onclick=()=>render(b.dataset.go));if(view==='customers'){const input=$('#customerSearch');input.oninput=()=>{$('#customerRows').innerHTML=customerRows(state.customers.filter(c=>c.join(' ').toLowerCase().includes(input.value.toLowerCase())));bindDeletes()};$('#addCustomer').onclick=()=>{const n=prompt('Nom du client :');if(!n)return;state.customers.unshift([n,'nouveau@client.fr','0','Actif']);save();render('customers');toast('Client ajouté.')};bindDeletes()}if(view==='transactions')$('#exportBtn').onclick=exportCSV;if(view==='rewards'){$('#addReward').onclick=()=>{const n=prompt('Nom de la récompense :');if(!n)return;state.rewards.push([n,300,0,true]);save();render('rewards')};$$('.reward-toggle').forEach(b=>b.onclick=()=>{state.rewards[b.dataset.i][3]=!state.rewards[b.dataset.i][3];save();render('rewards')})}if(view==='program'){['businessName','programName','rewardThreshold','rewardName','colorA','colorB'].forEach(id=>$('#'+id).oninput=updatePreview);$('#saveProgram').onclick=()=>toast('Programme enregistré.');$$('.wallet-add').forEach(b=>b.onclick=()=>toast('Mode démo : ajoutez vos certificats Wallet pour générer une vraie carte.'))}if(view==='scanner'){$('#addPoints').onclick=()=>{state.points+=10;state.transactions.unshift(['Yasine B.','+10','Gain','À l’instant']);save();$('#scanBalance').textContent=state.points+' pts';toast('10 points ajoutés.')};$('#useReward').onclick=()=>{if(state.points<300)return toast('Solde insuffisant pour cette récompense.');state.points-=300;state.transactions.unshift(['Yasine B.','-300','Récompense','À l’instant']);save();$('#scanBalance').textContent=state.points+' pts';toast('Récompense utilisée.')}}if(view==='employees')$('#inviteEmployee').onclick=()=>toast('Invitation employé envoyée en mode démo.');if(view==='settings')$('#saveSettings').onclick=()=>toast('Paramètres enregistrés.')}
function bindDeletes(){$$('.delete-customer').forEach(b=>b.onclick=()=>{state.customers.splice(+b.dataset.i,1);save();render('customers');toast('Client supprimé.')})}
function updatePreview(){const a=$('#colorA').value,b=$('#colorB').value;$('#previewCard').style.setProperty('--card-a',a);$('#previewCard').style.setProperty('--card-b',b);$('#pBusiness').textContent=$('#businessName').value;$('#pProgram').textContent=$('#programName').value;$('#pReward').textContent=`${$('#rewardThreshold').value} points = ${$('#rewardName').value}`}
function exportCSV(){const rows=[['Client','Mouvement','Type','Date'],...state.transactions];const csv=rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download='transactions-stampiio.csv';a.click();URL.revokeObjectURL(a.href);toast('Export CSV téléchargé.')}
